spring:
  application:
    name: demo-student-docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.1:5433/postgres
    username: kimheng
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
